using System;
using System.Linq;
using System.Collections.Generic;
using Qkmaxware.Measurement;

namespace Qkmaxware.Astro.Equipment {

public partial class Eyepiece {
    public static IEnumerable<Eyepiece> Catalogue => catalogue.AsReadOnly();

    public static List<Eyepiece> catalogue = new List<Eyepiece> {
        new Eyepiece {Manufacturer = "Agena",Model = "2\" Super Wide Angle (SWA)",FocalLength = Length.Millimetres(38.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Astro Essentials",Model = "Super Plossl",FocalLength = Length.Millimetres(7.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Astro Essentials",Model = "Super Plossl",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Astro-Tech",Model = "Titan",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Astro-Tech",Model = "Titan",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Classic Ortho",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Classic Ortho",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Classic Ortho",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Classic Plossl",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Eudiascopic",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(44.40)},
        new Eyepiece {Manufacturer = "Baader",Model = "Eudiascopic",FocalLength = Length.Millimetres(35.00),FieldOfView = Angle.Degrees(45.60)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(21.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion Aspheric",FocalLength = Length.Millimetres(31.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Baader",Model = "Hyperion Aspheric",FocalLength = Length.Millimetres(36.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(4.50),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(6.50),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "Baader Planetarium",Model = "Morpheus",FocalLength = Length.Millimetres(17.50),FieldOfView = Angle.Degrees(76.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(3.20),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "BST",Model = "Starguider",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Axiom",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Axiom",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "E-Lux",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(56.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "E-Lux",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(56.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "E-Lux 40mm",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(19.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(23.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Luminos",FocalLength = Length.Millimetres(31.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Plossl",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(43.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima",FocalLength = Length.Millimetres(7.50),FieldOfView = Angle.Degrees(51.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(51.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "Ultima Duo",FocalLength = Length.Millimetres(21.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(2.30),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Celestron",Model = "X-Cel LX",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(5.50),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "100° Series",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "120º Series",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(120.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(3.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(4.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(6.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "52° Series",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(5.50),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "62º Series",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Maxvision",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Maxvision",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Maxvision",FocalLength = Length.Millimetres(28.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Maxvision",FocalLength = Length.Millimetres(34.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Maxvision",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(28.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(34.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "68° Series",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "70º Series",FocalLength = Length.Millimetres(35.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Maxvision",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(4.70),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(6.70),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(8.80),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "82º Series",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "92° LER Series",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(92.00)},
        new Eyepiece {Manufacturer = "Explore Scientific",Model = "92° LER Series",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(92.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Fujiyama",Model = "HD-OR",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "GSO",Model = "2\" SuperView",FocalLength = Length.Millimetres(38.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "GSO",Model = "2\" SuperView Wide Angle",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "GSO",Model = "2\" SuperView Wide Angle",FocalLength = Length.Millimetres(42.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Kson",Model = "2” KF",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(46.00)},
        new Eyepiece {Manufacturer = "Kson",Model = "2” KF",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(46.00)},
        new Eyepiece {Manufacturer = "Kson",Model = "2” KF",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(46.00)},
        new Eyepiece {Manufacturer = "Lunt",Model = "H-alpha",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Lunt",Model = "H-alpha",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Lunt",Model = "H-alpha",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Lunt",Model = "H-alpha",FocalLength = Length.Millimetres(19.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Lunt",Model = "H-alpha",FocalLength = Length.Millimetres(27.00),FieldOfView = Angle.Degrees(53.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "1.25\" Eyepiece",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(85.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "2\" Eyepiece",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(85.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "2\" Eyepiece",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(85.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "2\" Eyepiece",FocalLength = Length.Millimetres(45.00),FieldOfView = Angle.Degrees(53.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "2\" Eyepiece",FocalLength = Length.Millimetres(50.00),FieldOfView = Angle.Degrees(53.00)},
        new Eyepiece {Manufacturer = "Masuyama",Model = "2\" Eyepiece",FocalLength = Length.Millimetres(60.00),FieldOfView = Angle.Degrees(46.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "4000 QX Wide Angle",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "5000 SWA",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "5000 UWA",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series 4000",FocalLength = Length.Millimetres(56.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series 4000 SWA",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(67.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series-5000 HD",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series-5000 HD",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series-5000 HD",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Series-5000 HD",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Super Plossl",FocalLength = Length.Millimetres(9.70),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Meade",Model = "Super Plossl",FocalLength = Length.Millimetres(12.40),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Orion",Model = "Expanse",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(66.00)},
        new Eyepiece {Manufacturer = "Orion",Model = "Q70",FocalLength = Length.Millimetres(38.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Ostara",Model = "SWA FMC",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Myriad",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Myriad",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Myriad",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Myriad",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Nirvana-ES UWA",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Nirvana-ES UWA",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Nirvana-ES UWA",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Panaview",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Panaview",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "OVL",Model = "Panaview",FocalLength = Length.Millimetres(38.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Pentax",Model = "XW",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Revelation",Model = "32mm Plossl",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Sky-Watcher",Model = "Aero ED SWA",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Sky-watcher",Model = "Super-MA",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Sky-watcher",Model = "Super-MA",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Sky-Watcher",Model = "Ultrawide",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(66.00)},
        new Eyepiece {Manufacturer = "Sky-watcher",Model = "UWA-Planetary",FocalLength = Length.Millimetres(2.50),FieldOfView = Angle.Degrees(58.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "15mm SuperView",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "20mm SuperView",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "30mm SuperView",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "42mm SuperView",FocalLength = Length.Millimetres(42.00),FieldOfView = Angle.Degrees(58.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "50mm SuperView",FocalLength = Length.Millimetres(50.00),FieldOfView = Angle.Degrees(48.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "8-24mm 1.25\" Lanthanum Zoom",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(40.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "8-24mm 1.25\" Lanthanum Zoom",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "8-24mm 1.25\" Lanthanum Zoom",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "KITAKARU RPL",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "KITAKARU RPL",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "KITAKARU RPL",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "KITAKARU RPL",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "KITAKARU RPL",FocalLength = Length.Millimetres(45.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "LER",FocalLength = Length.Millimetres(3.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "LER",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "LER",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "LER",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "LER",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "Super-Plossl",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "StellaLyra",Model = "Super-Plossl",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EOP-03.6",FocalLength = Length.Millimetres(3.60),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EOP-04.7",FocalLength = Length.Millimetres(4.70),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EOP-09.0",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EOP-13.5",FocalLength = Length.Millimetres(13.50),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EOP-20.0",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EUW-04.0",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EUW-08.0",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Stellarvue",Model = "EUW-15.0",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "Abbe",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(44.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(7.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "LE",FocalLength = Length.Millimetres(50.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "TOE",FocalLength = Length.Millimetres(2.50),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "TOE",FocalLength = Length.Millimetres(3.30),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Takahashi",Model = "TOE",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(52.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Apollo 11",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(85.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(3.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delite",FocalLength = Length.Millimetres(18.20),FieldOfView = Angle.Degrees(62.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(4.50),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Delos",FocalLength = Length.Millimetres(17.30),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(3.70),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(4.70),FieldOfView = Angle.Degrees(110.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Ethos",FocalLength = Length.Millimetres(21.00),FieldOfView = Angle.Degrees(100.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-5",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-5",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-5",FocalLength = Length.Millimetres(26.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-5",FocalLength = Length.Millimetres(31.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(2.50),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T-6",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T4",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T4",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T4",FocalLength = Length.Millimetres(22.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler T5",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler Zoom",FocalLength = Length.Millimetres(3.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler Zoom",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler Zoom",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Nagler Zoom",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(19.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(24.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(27.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(35.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Panoptic",FocalLength = Length.Millimetres(41.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(11.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(32.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(43.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Plössl",FocalLength = Length.Millimetres(55.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Radian",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "Tele Vue",Model = "Radian",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(60.00)},
        new Eyepiece {Manufacturer = "TS",Model = "NED",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "TS",Model = "NED",FocalLength = Length.Millimetres(18.00),FieldOfView = Angle.Degrees(68.00)},
        new Eyepiece {Manufacturer = "TS Optics",Model = "Planetary HR",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(58.00)},
        new Eyepiece {Manufacturer = "TS Optics",Model = "Superview 40mm 1.25\"",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(46.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "HR",FocalLength = Length.Millimetres(1.60),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "HR",FocalLength = Length.Millimetres(2.00),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "HR",FocalLength = Length.Millimetres(2.40),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "HR",FocalLength = Length.Millimetres(3.40),FieldOfView = Angle.Degrees(42.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(13.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(17.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(22.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "LVW",FocalLength = Length.Millimetres(42.00),FieldOfView = Angle.Degrees(65.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(8.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(30.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "NPL (Plossl)",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(40.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(2.50),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(12.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(20.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SLV",FocalLength = Length.Millimetres(25.00),FieldOfView = Angle.Degrees(50.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SSW",FocalLength = Length.Millimetres(3.50),FieldOfView = Angle.Degrees(83.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SSW",FocalLength = Length.Millimetres(5.00),FieldOfView = Angle.Degrees(83.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SSW",FocalLength = Length.Millimetres(7.00),FieldOfView = Angle.Degrees(83.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SSW",FocalLength = Length.Millimetres(10.00),FieldOfView = Angle.Degrees(83.00)},
        new Eyepiece {Manufacturer = "Vixen",Model = "SSW",FocalLength = Length.Millimetres(14.00),FieldOfView = Angle.Degrees(83.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "SPL",FocalLength = Length.Millimetres(3.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "SPL",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "SPL",FocalLength = Length.Millimetres(12.50),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "SWAN",FocalLength = Length.Millimetres(9.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "SWAN",FocalLength = Length.Millimetres(15.00),FieldOfView = Angle.Degrees(72.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "UWAN",FocalLength = Length.Millimetres(16.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "UWAN",FocalLength = Length.Millimetres(28.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "William Optics",Model = "UWAN",FocalLength = Length.Millimetres(28.00),FieldOfView = Angle.Degrees(82.00)},
        new Eyepiece {Manufacturer = "Williams optics",Model = "SPL",FocalLength = Length.Millimetres(6.00),FieldOfView = Angle.Degrees(55.00)},
        new Eyepiece {Manufacturer = "Williams Optics",Model = "SWAN",FocalLength = Length.Millimetres(40.00),FieldOfView = Angle.Degrees(70.00)},
        new Eyepiece {Manufacturer = "Williams Optics",Model = "UWAN",FocalLength = Length.Millimetres(4.00),FieldOfView = Angle.Degrees(82.00)},

    };

}

}